"""添加粉丝关注功能

Revision ID: 469a3271458a
Revises: 3f79774abe44
Create Date: 2018-09-18 12:12:14.800431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469a3271458a'
down_revision = '3f79774abe44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('fan_id', sa.Integer(), nullable=True),
    sa.Column('star_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['star_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
